config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :comments, shallow: true, only: [:create, :destroy]
    # member do
    #   post :like
    # end
  end

  resource :users, except: %i[destroy] do
    collection do
      get :sign_in
    end
  end

  resource :sessions, only: [:create, :destroy]
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :price, numericality: { greater_than: 0 }

  belongs_to :user

  has_many :comments, ->{ order(id: :desc) }
  has_many :like_books
  has_many :liked_user, through: :like_books, source: :user

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.current)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/like_book.rb
class LikeBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true,
  confirmation: true

  has_many :books
  has_many :comments

  has_many :like_books
  has_many :liked_books, through: :like_books, source: :book

  before_create :encrypt_password

  def own?(b)
    book_ids.include?(b.id)
  end

  def self.login(data)
    email = data[:email]
    password = do_encrypt(data[:password])
    find_by(email: , password: )
  end

  def self.do_encrypt(target)
    salted_password = "*xx#{target}yy-"
    Digest::SHA256.hexdigest(salted_password)
  end

  private

  def encrypt_password
    self.password = self.class.do_encrypt(self.password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  helper_method :user_signed_in?, :current_user

  private
  
  def current_user
    @__user__ ||= User.find_by(id: session[:__user_ticket__])
  end

  def user_signed_in?
    current_user.present?
  end

  def not_found
    render file: Rails.public_path.join('404.html'),status: 404
  end

  def authenticate_user!
    if not user_signed_in?
      redirect_to sign_in_users_path, alert: "請先登入"
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = Book.order(id: :desc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(set_book)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @book.comments
  end

  def edit
  end

  def update
    if @book.update(set_book)
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def find_book
    @book = Book.find(params[:id])
  end

  def set_book
    params.require(:book).permit(:title, :description, :price)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    # logger.debug "create post: #{params}"
    book = Book.find(params[:book_id])
    comment = book.comments.new(comment_params)

    if comment.save
      redirect_to book_path(book), notice: '新增留言成功'
    else
      redirect_to book_path(book), alert: '留言發生錯誤'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.login(params[:user])
    if user
      session[:__user_ticket__] = user.id
      redirect_to root_path, notice: "登入成功"
    else
      redirect_to root_path, alert: "登入失敗"
    end
  end

  def destroy
    session.delete(:__user_ticket__)
    redirect_to root_path, notice: "已登出"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(set_user)
    if @user.save
      redirect_to root_path, notice: "註冊成功"
    else
      render :new
    end
  end

  def sign_in
  end

  def set_user
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<section class="ml-2 text-lg">
    <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
    <% end %>
    <%= form_with model:@book, data: { turbo: false} do |f| %>
        <div>
            <%= f.label :title %>
            <%= f.text_field :title, class: 'field' %>
        </div>
        <div>
            <%= f.label :price %>
            <%= f.number_field :price, class: 'field' %>
        </div>
        <div>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'field' %>
        </div>
        <div>
            <%= f.submit class: 'btn' %>
        </div>
    <% end %>
</section>

app/views/books/index.html.erb
<% if user_signed_in? %>
    <%= link_to "新增", new_book_path, class: "btn"%>
<% end %>
<ul class="ml-2 text-lg">
    <% @books.each do |book| %>
        <li>[<%= book.user.email %>]<%= link_to book.title, book_path(book) %></li>
    <% end %>
</ul>

app/views/books/new.html.erb
<% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |message| %>
        <div class="alert"><%= message %></div>
    <% end %>
<% end %>
<%= form_with model:@book, data: { turbo: false} do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'field' %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.number_field :price, class: 'field' %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'field' %>
    </div>
    <div>
        <%= f.submit class: 'btn' %>
    </div>
<% end %>

app/views/books/show.html.erb
<% if user_signed_in? and current_user.own?(@book) %>
    <%= link_to "編輯", edit_book_path(@book), class: "btn" %>
    <%= link_to "刪除", book_path(@book), data:{
        turbo_method: "delete",
        turbo_confirm: "確定刪除？"
    }, class: "btn danger" %>
<% end %>
<section class="text-lg">
    <h1 class="flex items-center gap-2 text-2xl">
        Title:<%= @book.title %>
        <div data-controller="like"
            data-id="<%= @book.id %>" 
            >
            <%= link_to('#', data:{ action: 'like#toggle', like_target: 'btn'}) do %>
                <%= image_tag "/images/unfavourite.png", style: 'height:20px;'%>
            <% end %>
        </div>
    </h1>
    <h3>Price:<%= @book.price %></h3>
    <label>
        Description:
        <p>
            <%= simple_format @book.description %>
        </p>
    </label>
</section>
<section class="text-lg bg-slate-100 rounded">
    <% if user_signed_in? and not current_user.own?(@book) %>        
        <h4>留言:</h4>
        <%= form_with model:[@book, @comment], data: { turbo: false } do |f|  %>
            <%= f.text_area :content, class: 'field' %>        
            <div>
            <%= f.submit '新增留言', class:'btn'%>
            </div>
        <% end %>
    <% end %>
    <ul>
        <% @comments.each.with_index(1) do |c, index| %>
        <li>
            <div><%= "\##{index} #{c.content}" %></div>
            <div>by <%= c.user.email.split("@").first %></div>
            <div>at <%= c.created_at.strftime("%Y/%m/%d %I:%M %p") %></div>
        </li>            
        <% end %>
    </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <div class="container m-auto mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% [:notice, :alert].each do |type| %>
    <% if flash[type] %>
    <div class="<%= type %>">
        <%= flash[type] %>
    </div>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex justify-between bg-teal-800 text-white px-24 py-3">
    <div>
        <h1 class="font-black"><%= link_to "BookS", root_path %></h1>
    </div>
    <ul class="flex gap-3">
        <% if user_signed_in? %>
            <li><%= current_user.email %></li>
            <li><%= link_to "登出", sessions_path, data: { turbo_method: "delete" } %></li>
        <% else %>
            <li><%= link_to "註冊", new_users_path %></li>
            <li><%= link_to "登入", sign_in_users_path %></li>
        <% end %>
    </ul>
</nav>

app/views/users/new.html.erb
<% if @user.errors.any? %>
<div class="alert">
    <% @user.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <% end %>
</div>
<% end %>
<section>
<%= form_with model:@user, data: { turbo: false } do |f| %>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'field' %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'field' %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'field' %>
    </div>
    <div>
        <%= f.submit class:'btn'%>
    </div>
<% end %>
</section>

app/views/users/sign_in.html.erb
<h1 class="text-2xl">登入</h1>
<%= form_with(url: sessions_path, scope: 'user', data: { turbo: false }) do |f| %>
<div>
    <%= f.label :email %>
    <%= f.email_field :email , class: "field" %>
</div>
<div>
    <%= f.label :password %>
    <%= f.password_field :password , class: "field" %>
</div>
<div>
    <%= f.submit '登入', class: "btn"%>
</div>
<% end %>